exp = operations
<operations> = sum | sub | mul | div
mul = term <'*'> term
div = term <'/'> term
sum = term <'+'> term
sub = term <'-'> term
number = #'\s*[0-9]+\s*'
<term> = number | <#'\s*' '('> operations <')' #'\s*'> | operations